overhaul makefiles
- Fix EXESUFFIX on %.so rule; remove TBD

- Linux: Add -Wl,-E flags so that symbols within static swish
  executable can satisfy dependencies, such as Scons, of shared
  libraries we load via load-shared-object.

  For example, suppose libfoo.so uses Scons. If we omit the -Wl,-E
  flags, then we have a confusing situation where:

    $ nm $(which scheme) | grep Scons
    00000000004091e0 T Scons
    $ nm $(which swish) | grep Scons
    0000000000499f90 T Scons
    $ echo '(load-shared-object "./libfoo.so")' | scheme  # okay
    $ echo '(load-shared-object "./libfoo.so")' | swish
    Exception: (while loading ./libfoo.so) ./libfoo.so: undefined symbol: Scons

- Windows: Experimented with /MT and /MD; settled on the latter.

- Windows: Add /ltcg to fix link warning against libuv on Windows.

- Windows: allow environment variable overrides of SchemeDir,
  SchemeInclude, and SchemeLib

- Made dependencies more precise, e.g., depend on libuv.a rather
  than the target directory containing libuv.a.

allow environment override of